export ATISTREAMSDKROOT=$HOME/Programs/ati-stream-sdk-v2.2-lnx64
export PATH=$ATISTREAMSDKROOT/bin/x86_64:$PATH
export LD_LIBRARY_PATH=$ATISTREAMSDKROOT/lib/x86_64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$ATISTREAMSDKROOT/lib/x86:$LD_LIBRARY_PATH
